"""
Django settings for bank_config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
load_dotenv(PROJECT_ROOT / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "BANK_DJANGO_SECRET_KEY",
    "django-insecure-mock-bank-dev-secret-key-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv("BANK_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bank_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bank_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('BANK_DB_NAME', 'mock_bank_service'),
        'USER': os.getenv('BANK_DB_USERNAME', os.getenv('DB_USERNAME', 'root')),
        'PASSWORD': os.getenv('BANK_DB_PASSWORD', os.getenv('DB_PASSWORD', '')),
        'HOST': os.getenv('BANK_DB_HOST', os.getenv('DB_HOST', 'localhost')),
        'PORT': os.getenv('BANK_DB_PORT', os.getenv('DB_PORT', '3306')),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

def _parse_key_map(raw_value):
    return {
        item.split(":", 1)[0]: item.split(":", 1)[1]
        for item in raw_value.split(",")
        if ":" in item
    }


BANK_PAYMENT_TIMESTAMP_VALID_SECONDS = int(os.getenv("BANK_PAYMENT_TIMESTAMP_VALID_SECONDS", "300"))

BANK_MERCHANT_PRIVATE_KEYS = _parse_key_map(
    os.getenv(
        "BANK_MERCHANT_PRIVATE_KEYS",
        "ECOMMERCE_DEMO:a96e3fd619a89a6c239d84435c4c174f35439f8fb1f3d0b773d505c4aa75265c",
    )
)
BANK_MERCHANT_PUBLIC_KEYS = _parse_key_map(
    os.getenv(
        "BANK_MERCHANT_PUBLIC_KEYS",
        "ECOMMERCE_DEMO:a88b6f2d32e6df38e94f3e627af9ac4e576d7ca91beeeb2d1f1d925119e9913fea9a6a857e97cf2caa36e2b05da5373d26e0ec2bc2649b959c98da3755235216",
    )
)
BANK_MERCHANT_CALLBACK_URLS = _parse_key_map(
    os.getenv(
        "BANK_MERCHANT_CALLBACK_URLS",
        "ECOMMERCE_DEMO:http://127.0.0.1:8080/api/pay/callback",
    )
)

BANK_USER_PRIVATE_KEYS = _parse_key_map(
    os.getenv(
        "BANK_USER_PRIVATE_KEYS",
        "demo_user:12601231018c621b737098ff61d3b450771617e54820e7f69ad411fd4106fda7",
    )
)
BANK_USER_PUBLIC_KEYS = _parse_key_map(
    os.getenv(
        "BANK_USER_PUBLIC_KEYS",
        "demo_user:fb0ef592e01b03601165b368385e0624c87aed2be6d361d1ecc88c62ab66597e43646080710a4e7e5b6e16b59615a3248be65a4de82afe9f838b1411980858dc",
    )
)
